name: Relay Control

on:
  schedule:
    - cron: '*/2 * * * *'  # Menjalankan setiap dua menit

jobs:
  control_relay:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kode
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Ganti dengan versi Python yang sesuai

    - name: Menyalakan relay
      run: |
        # Import library HTTP untuk mengirim permintaan HTTP
        import requests

        # Token API dan URL untuk menyalakan relay
        token = 'hsoqoqt9FAJb7B_CkMv9qHe5ei94zPUp'
        url_on = 'https://sgp1.blynk.cloud/external/api/update?token=' + token + '&v1=1'

        # Mengirim permintaan HTTP untuk menyalakan relay
        response = requests.get(url_on)

        # Menunggu 20 detik
        import time
        time.sleep(20)

        # URL untuk mematikan relay
        url_off = 'https://sgp1.blynk.cloud/external/api/update?token=' + token + '&v1=0'

        # Mengirim permintaan HTTP untuk mematikan relay
        response = requests.get(url_off)

    - name: Selesai
